name: 🚀 Make release

on:
  push:
    tags:
      - 'v*' # Triggers on tags like v1.0.0

jobs:
  build_and_release:
    # macOS runner is required to use xcodebuild
    runs-on: macos-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Select Xcode Version
        run: sudo xcode-select -switch /Applications/Xcode.app

      - name: Build CLI Tool
        run: |
          xcodebuild -project "Valistream/Valistream/Valistream.xcodeproj" \
                     -scheme "Valistream" \
                     -configuration Release \
                     -derivedDataPath BuildData \
                     build
                     
      - name: Compress Binary
        run: |
          # Find binary in the build directory and zip it
          cd BuildData/Build/Products/Release/
          zip -r ../../../../valistream-cli.zip ./valistream

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: valistream-cli.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
